// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkwraysdozypqxygfmqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrd3JheXNkb3p5cHF4eWdmbXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDc1MzksImV4cCI6MjA3MjE4MzUzOX0.EjIYuVol18BOH-TVQhr74gi1-tXP6Qbo69ZUM8Urrf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});